#include <vector>
#include <iostream>
#include "gerenciador.h"

int main()
{
    Gerenciador gerente(10);
    // gerente.render.renderizar(gerente.cenario)
    
    
    // turno...
    // renderiza ...
    // turno...
    // renderiza ...
    // turno...
    // renderiza ...
}