#include <vector>
#include <iostream>
#include "gerenciador.h"

int main()
{
    Gerenciador gerente(10);
    Cenario& c = gerente.getCenario();
    gerente.render.renderizar(c);
    
    
    // turno...
    // renderiza ...
    // turno...
    // renderiza ...
    // turno...
    // renderiza ...
}